export const SET_SHOWS_DATA = 'SET_SHOWS_DATA';
export const SET_IS_LOADING_SHOW_DATA = 'SET_IS_LOADING_SHOW_DATA';

export const SET_MOVIES_DATA = 'SET_MOVIES_DATA';
export const SET_IS_LOADING_MOVIES_DATA = 'SET_IS_LOADING_MOVIES_DATA';

